language: swift
osx_image: xcode10.2
podfile: LLAEasyAlertManagerDemo/Podfile

script:
  - swift --version
  - xcodebuild test -workspace "LLAEasyAlertManagerDemo/LLAEasyAlertManagerDemo.xcworkspace" -scheme "LLAEasyAlertManagerDemo" -sdk iphonesimulator -destination "platform=iOS Simulator,name=iPhone X" -configuration Debug

branches:
  only: 
      - master
